{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "25aa5c23-b7ab-40ef-bbad-5045705aeca2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "\n",
    "class Employee:\n",
    "    def __init__(self, emp_id, name, role, pay_rate, hours_worked):\n",
    "        self.id = emp_id\n",
    "        self.name = name\n",
    "        self.role = role\n",
    "        self.pay_rate = float(pay_rate)\n",
    "        self.hours_worked = float(hours_worked)\n",
    "\n",
    "    def calculate_salary(self):\n",
    "        # Math logic replacing Excel formulas\n",
    "        if self.role.lower() == \"hourly\":\n",
    "            if self.hours_worked > 40:\n",
    "                regular_pay = 40 * self.pay_rate\n",
    "                overtime_hours = self.hours_worked - 40\n",
    "                overtime_pay = overtime_hours * (self.pay_rate * 1.5)\n",
    "                gross_pay = regular_pay + overtime_pay\n",
    "            else:\n",
    "                gross_pay = self.hours_worked * self.pay_rate\n",
    "        else:\n",
    "            # Salaried employees get a flat monthly rate\n",
    "            gross_pay = self.pay_rate\n",
    "\n",
    "        tax = gross_pay * 0.10  # 10% Income Tax deduction\n",
    "        net_pay = gross_pay - tax\n",
    "        return gross_pay, tax, net_pay\n",
    "\n",
    "\n",
    "class PayrollSystem:\n",
    "    def __init__(self, filename=\"employees.csv\"):\n",
    "        self.filename = filename\n",
    "\n",
    "    def load_employees(self):\n",
    "        \"\"\"Reads data from the CSV file\"\"\"\n",
    "        employees = []\n",
    "        try:\n",
    "            with open(self.filename, mode='r') as file:\n",
    "                reader = csv.DictReader(file)\n",
    "                for row in reader:\n",
    "                    emp = Employee(row['id'], row['name'], row['role'], row['pay_rate'], row['hours_worked'])\n",
    "                    employees.append(emp)\n",
    "        except FileNotFoundError:\n",
    "            print(\"Error: employees.csv file not found. Creating a new one.\")\n",
    "        return employees\n",
    "\n",
    "    def save_employee(self, emp_id, name, role, pay_rate, hours_worked):\n",
    "        \"\"\"Appends a new employee row to the CSV file\"\"\"\n",
    "        fields = ['id', 'name', 'role', 'pay_rate', 'hours_worked']\n",
    "        with open(self.filename, mode='a', newline='') as file:\n",
    "            writer = csv.DictWriter(file, fieldnames=fields)\n",
    "            writer.writerow({\n",
    "                'id': emp_id,\n",
    "                'name': name,\n",
    "                'role': role,\n",
    "                'pay_rate': pay_rate,\n",
    "                'hours_worked': hours_worked\n",
    "            })\n",
    "\n",
    "    def generate_report(self):\n",
    "        \"\"\"Processes and prints the payroll dashboard\"\"\"\n",
    "        employees = self.load_employees()\n",
    "        if not employees:\n",
    "            print(\"\\n[!] No employee data found.\")\n",
    "            return\n",
    "\n",
    "        print(\"\\n\" + \"=\"*60)\n",
    "        print(f\"{'ID':<6} | {'Name':<15} | {'Role':<10} | {'Gross':<10} | {'Tax':<8} | {'Net Pay':<10}\")\n",
    "        print(\"=\"*60)\n",
    "\n",
    "        total_payout = 0\n",
    "        for emp in employees:\n",
    "            gross, tax, net = emp.calculate_salary()\n",
    "            total_payout += net\n",
    "            print(f\"{emp.id:<6} | {emp.name:<15} | {emp.role:<10} | ${gross:<9.2f} | ${tax:<7.2f} | ${net:<9.2f}\")\n",
    "        \n",
    "        print(\"=\"*60)\n",
    "        print(f\"Total Company Outflow: ${total_payout:,.2f}\")\n",
    "        print(\"=\"*60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4e3e9263-4dd8-481f-98b1-2b39552a03a6",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'payroll'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpayroll\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m PayrollSystem\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mmain_menu\u001b[39m():\n\u001b[32m      4\u001b[39m     system = PayrollSystem()\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'payroll'"
     ]
    }
   ],
   "source": [
    "from payroll import PayrollSystem\n",
    "\n",
    "def main_menu():\n",
    "    system = PayrollSystem()\n",
    "\n",
    "    while True:\n",
    "        print(\"\\n--- PAYROLL MANAGEMENT SYSTEM ---\")\n",
    "        print(\"1. View Payroll Report\")\n",
    "        print(\"2. Add New Employee\")\n",
    "        print(\"3. Exit Program\")\n",
    "        \n",
    "        choice = input(\"Enter your choice (1-3): \").strip()\n",
    "\n",
    "        if choice == \"1\":\n",
    "            system.generate_report()\n",
    "        \n",
    "        elif choice == \"2\":\n",
    "            print(\"\\n--- Register New Employee ---\")\n",
    "            emp_id = input(\"Enter Employee ID: \")\n",
    "            name = input(\"Enter Name: \")\n",
    "            role = input(\"Enter Role (Salaried / Hourly): \")\n",
    "            pay_rate = input(\"Enter Pay Rate (Monthly Salary or Hourly Wage): \")\n",
    "            \n",
    "            if role.lower() == \"hourly\":\n",
    "                hours_worked = input(\"Enter Hours Worked this month: \")\n",
    "            else:\n",
    "                hours_worked = 0  # Salaried employees don't track hourly clocks here\n",
    "                \n",
    "            system.save_employee(emp_id, name, role, pay_rate, hours_worked)\n",
    "            print(f\"\\n[+] Success: {name} added to payroll database.\")\n",
    "            \n",
    "        elif choice == \"3\":\n",
    "            print(\"\\nExiting program. Thank you!\")\n",
    "            break\n",
    "        else:\n",
    "            print(\"\\nInvalid choice! Please enter 1, 2, or 3.\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main_menu()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9230df8-0ddc-4523-8ba2-9301b4ffac44",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
